from enum import Enum, auto


class Attribute(Enum):
    Strength = auto()
    Dexterity = auto()
    Stamina = auto()


class Ability(Enum):
    Alertness = auto()
    Athletics = auto()
    Awareness = auto()
    Brawl = auto()
    Empathy = auto()
    Expression = auto()
    Intimidation = auto()
    Leadership = auto()
    Streetwise = auto()
    Subterfuge = auto()
    Hobby_Talent = auto()
    Animal_Ken = auto()
    Crafts = auto()
    Drive = auto()
    Etiquette = auto()
    Firearms = auto()
    Larceny = auto()
    Melee = auto()
    Performance = auto()
    Stealth = auto()
    Survival = auto()
    Academics = auto()
    Computer = auto()
    Finance = auto()
    Investigation = auto()
    Law = auto()
    Medicine = auto()
    Occult = auto()
    Politics = auto()
    Science = auto()
    Technology = auto()
