

Ability = [
    "Alertness",
    "Athletics",
    "Awareness",
    "Brawl",
    "Empathy",
    "Expression",
    "Intimidation",
    "Leadership",
    "Streetwise",
    "Subterfuge",
#    "Hobby Talent",
    "Animal Ken",
    "Crafts",
    "Drive",
    "Etiquette",
    "Firearms",
    "Larceny",
    "Melee",
    "Performance",
    "Stealth",
    "Survival",
    "Academics",
    "Computer",
    "Finance",
    "Investigation",
    "Law",
    "Medicine",
    "Occult",
    "Politics",
    "Science",
    "Technology"
]
